### ISSUE TITLE
BlackFly 5 MP Camera

### ISSUE THREAD

**Issue by burritobrittany** [Coastal-Imaging-Research-Network/station-design-toolbox#10]
Hi Kara,
I have a student who is using the toolbox. What a great tool with great documentations, thanks!

We noticed we were getting some odd results using the standard BlackFly 5 MP option from the pull down menu.  We think the Pixel Pitch may be off in the m-file that has the default camera lists. I believe the code currently has it as 1.2*10^3. Going off the FLIR specifications, I believe it should be 3.45. It seems minor...but it had huge implications on our footprint. It also may just be a different sensor size between all of the different models of BlackFlys. 

Not sure if it warrants a change in the code...but I figured I would post the issue in case someone else has this problem. 

Again, we would not have been able to troubleshoot so quickly if it was not for your great manual!!

Brittany

**Comment by kkoetje** [comment]
Thanks for catching that, @burritobrittany ! I expect that was either a typo or a holdover from an old lcp file list that is now out of date. I'll push an edited cam list to fix that error.

My hope is that the cam list is an evolving file that is added to as people work with an expanding list of cameras!
