### ISSUE TITLE
undefined function fov

### ISSUE THREAD

**Issue by AthinaLange** [Coastal-Imaging-Research-Network/station-design-toolbox#12]
Hi Kara,
This toolbox seems like it would be a lot of help in planning our next experiment, but I keep getting an error in 'StationDesignGui/PlotCameraFootprintButtonPushed (line 194)', 'Undefined function 'fov' for input arguments of type 'double'.'

I'm not sure if I'm missing something, or if I need to download something else (besides the OpenEarth Toolbox).

Thanks,
Athina

**Comment by kkoetje** [comment]
Hi Athina,
'fov.m' is included in the CIRN Support Routines repository, which is needed to run the Station Design Toolbox GUI. Take a look at the Station Design Toolbox User Manual for more info. If you already have the Support Routines repo cloned or saved to your machine, check that that the local path you enter into the field towards the bottom of the GUI window accurately points to your Support Routines folder. Hope this helps!
-Kara
