### ISSUE TITLE
Multi-cam station with different focal lengths?

### ISSUE THREAD

**Issue by SRHarrison** [Coastal-Imaging-Research-Network/station-design-toolbox#3]
Hi Kara, 
This looks like a super helpful and tidy toolbox. One question that I couldn't seem to figure out - how do we specify multiple focal lengths for situations when each camera within a single station uses a different focal length (e.g. 2 camera station with fl=8mm on cam1 and fl=12mm on cam2)?

Thanks for this great contribution!

**Comment by kkoetje** [comment]
Hi Shawn,
This first iteration of the tool assumes the same focal lengths and sensor size for all cameras in the array.  However, I plan to add the ability to specify different specs for each camera soon.  Thanks for checking it out!  Please let me know if there is any other functionality you'd like to see included in future versions.
-Kara

**Comment by eswanson-usgs** [comment]
Closing this issue and rolling into issue #11 as they relate to the same issue
