### ISSUE TITLE
pan?

### ISSUE THREAD

**Issue by RobHolman** [Coastal-Imaging-Research-Network/station-design-toolbox#4]
Nice tool, professionally done with good documentation.  Thanks.

I did have a problem with plot Camera Footprint, which caused "Error using pan (line 199)
Functionality not supported with figures created with the uifigure function."  Maybe it is because I'm using Matlab2016??  I'm not good at the git stuff so I might have screwed up.  

Of course it would be great to have mixed focal lengths cuz this is common in station design (closer usually wider fov) but that could be version 2.

**Comment by kkoetje** [comment]
Hi @RobHolman , I haven't come across that error, but based on several forum posts, pan and zoom errors appear to be related to Matlab2016.  You may be able to comment out line 214 and perhaps also line 215 if needed.  To make changes to the app script using App Designer Editor, go to the Matlab Home tab, click Open, and select StationDesignGui.mlapp.  Once the App Designer window opens, choose Code View in the right hand corner.
